### PR TITLE
reformat allocation

### PR DESCRIPTION
**Pull request by rolandpo**
reformat the way strategy allocation gets displayed, and prevent problems from changing backend strategy list

related PR: https://github.com/OriginProtocol/ousd-analytics/pull/261

### CODE REVIEW

**Comment by franckc** [comment]
@rolandpo @shahthepro Is this PR still active?

**Comment by rolandpo** [comment]
I should be, it prevents errors from changes in analytics and automates strategy grouping a little bit better. It would need an analytics deploy to pick up strategy name changes first though

**Review by shahthepro — CHANGES_REQUESTED** [review]
@rolandpo It would be great to clean up the use of `protocol.name` and `strategy.name` in the repo with this PR (since it already touches the relevant code).

Rather than using [`/api/v1/strategies`](https://analytics.ousd.com/api/v1/strategies), you can use [`/api/v1/strategies?structured=true`](https://analytics.ousd.com/api/v1/strategies?structured=true)

**Comment by rolandpo** [comment]
could the structured endpoint be edited somehow? i think the previous one made it easier to group strategies by protocol, since there's fewer allocations visually then there are separate strategies and i don't think it's super simple to infer how these are grouped in code

**Comment by franckc** [comment]
@rolandpo Let's prioritize this since it was the root cause for the [ousd.com site outage](https://docs.google.com/document/d/1S5xwW3gN-rvTO8YK1zojvLxjdRUomAiTZcsGvEOADOo/edit) last week. Thanks! :)

Note: Tom's short-term fix was merged. See https://github.com/OriginProtocol/ousd.com/pull/75

**Comment by rolandpo** [comment]
outdated

**Pull request closed without merging**
