### PR TITLE
Prevent client dying when strategy isn't found

### PR DESCRIPTION
**Pull request by tomhirst**

### CODE REVIEW

**Comment by HrikB** [comment]
@tomhirst Can you sign your commit so this can be merged?

**Comment by tomhirst** [comment]
> @tomhirst Can you sign your commit so this can be merged?

I've signed the commit, but could you confirm this has been tested as working before merging please?

I didn't get chance to set up properly locally when we were rushing to find a fix.

Thanks, Hrik!

**Comment by HrikB** [comment]
Sounds good will try it out.

**Comment by HrikB** [comment]
Ok `?` needed to be added to Collateral.js as well otherwise if `strategyMapping[strategy.name]` returns `undefined`, home page load fails. This should suffice while we implement error handling as a longer term solution. 

Will merge now.

**Pull request merged**
