### PR TITLE
animated tvl

### PR DESCRIPTION
**Pull request by rolandpo**
adds animation to the main ousd tvl number, based on the current value of underlying collateral

since the pending yield goes up by a fraction of a dollar per block and the tvl number is truncated, the animation isn't all that impressive

can add two decimals places potentially, thought that looks a bit messy

### CODE REVIEW

**Comment by rolandpo** [comment]
added dripper funds

**Comment by micahalcorn** [comment]
> adds animation to the main ousd tvl number, based on the current value of underlying collateral
> 
> since the pending yield goes up by a fraction of a dollar per block and the tvl number is truncated, the animation isn't all that impressive
> 
> can add two decimals places potentially, thought that looks a bit messy

Oh, interesting 😕 I thought it was faster than that, but I guess it takes close to one minute to increment by a dollar?

**Comment by rolandpo** [comment]
yep, something like 45s probably

**Comment by micahalcorn** [comment]
> yep, something like 45s probably

I'd be okay with adding the two decimal places for now. I think what we might do is move the APY up above the fold and move this down, in which case it won't get as much attention.

**Comment by rolandpo** [comment]
added

**Review by sparrowDom — APPROVED** [review]
Sweet LGTM, nice touch on the refactoring contract stuff out of Contracts component

**Comment by sparrowDom** [comment]
@rolandpo also have changed base branch to `rolandpo/chain` so that the diff is easier to look at. Feel free to merge this in. Would probably be easier to merge this PR in first and then the one based on the `rolandpo/chain` branch.

**Pull request merged**
