### PR TITLE
add gtm

### PR DESCRIPTION
**Pull request by rolandpo**
add google tag manager code
also remove previously added google analytics code for consistency

### CODE REVIEW

**Comment by jonathansnow** [comment]
GTM ID for this deployment is **GTM-K2LDMRW**

**Comment by franckc** [comment]
> GTM-K2LDMRW

I have set NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID to GTM-K2LDMRW on Heroku for both staging and prod.

**Review by sparrowDom — APPROVED** [review]
LGTM

**Comment by sparrowDom** [comment]
thanks for setting the env vars on Heroku Franck!

**Pull request merged**
